#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure_ac
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : munge
Version  : 0.5.16
Release  : 16
URL      : https://github.com/dun/munge/archive/munge-0.5.16/munge-0.5.16.tar.gz
Source0  : https://github.com/dun/munge/archive/munge-0.5.16/munge-0.5.16.tar.gz
Summary  : MUNGE authentication service library
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: munge-bin = %{version}-%{release}
Requires: munge-lib = %{version}-%{release}
Requires: munge-license = %{version}-%{release}
Requires: munge-man = %{version}-%{release}
Requires: munge-services = %{version}-%{release}
BuildRequires : bzip2-dev
BuildRequires : file
BuildRequires : openssl-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : sed
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Add-munge-var-paths-to-tmpfiles-config.patch

%description
INTRODUCTION
MUNGE (MUNGE Uid 'N' Gid Emporium) is an authentication service for
creating and validating user credentials.  It is designed to be highly
scalable for use in an HPC cluster environment.  It provides a portable
API for encoding the user's identity into a tamper-proof credential
that can be obtained by an untrusted client and forwarded by untrusted
intermediaries within a security realm.  Clients within this realm can
create and validate credentials without the use of root privileges,
reserved ports, or platform-specific methods.

%package bin
Summary: bin components for the munge package.
Group: Binaries
Requires: munge-license = %{version}-%{release}
Requires: munge-services = %{version}-%{release}

%description bin
bin components for the munge package.


%package dev
Summary: dev components for the munge package.
Group: Development
Requires: munge-lib = %{version}-%{release}
Requires: munge-bin = %{version}-%{release}
Provides: munge-devel = %{version}-%{release}
Requires: munge = %{version}-%{release}

%description dev
dev components for the munge package.


%package lib
Summary: lib components for the munge package.
Group: Libraries
Requires: munge-license = %{version}-%{release}

%description lib
lib components for the munge package.


%package license
Summary: license components for the munge package.
Group: Default

%description license
license components for the munge package.


%package man
Summary: man components for the munge package.
Group: Default

%description man
man components for the munge package.


%package services
Summary: services components for the munge package.
Group: Systemd services
Requires: systemd

%description services
services components for the munge package.


%prep
%setup -q -n munge-munge-0.5.16
cd %{_builddir}/munge-munge-0.5.16
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720056020
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%reconfigure --disable-static --with-crypto-lib=openssl
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720056020
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/munge
cp %{_builddir}/munge-munge-%{version}/COPYING %{buildroot}/usr/share/package-licenses/munge/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/munge-munge-%{version}/COPYING.LESSER %{buildroot}/usr/share/package-licenses/munge/e203d4ef09d404fa5c03cf6590e44231665be689 || :
export GOAMD64=v2
GOAMD64=v2
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/munge
/usr/bin/munged
/usr/bin/mungekey
/usr/bin/remunge
/usr/bin/unmunge

%files dev
%defattr(-,root,root,-)
/usr/include/munge.h
/usr/lib64/libmunge.so
/usr/lib64/pkgconfig/munge.pc
/usr/share/man/man3/munge.3
/usr/share/man/man3/munge_ctx.3
/usr/share/man/man3/munge_ctx_copy.3
/usr/share/man/man3/munge_ctx_create.3
/usr/share/man/man3/munge_ctx_destroy.3
/usr/share/man/man3/munge_ctx_get.3
/usr/share/man/man3/munge_ctx_set.3
/usr/share/man/man3/munge_ctx_strerror.3
/usr/share/man/man3/munge_decode.3
/usr/share/man/man3/munge_encode.3
/usr/share/man/man3/munge_enum.3
/usr/share/man/man3/munge_enum_int_to_str.3
/usr/share/man/man3/munge_enum_is_valid.3
/usr/share/man/man3/munge_enum_str_to_int.3
/usr/share/man/man3/munge_strerror.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmunge.so.2
/usr/lib64/libmunge.so.2.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/munge/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/munge/e203d4ef09d404fa5c03cf6590e44231665be689

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/munge.1
/usr/share/man/man1/remunge.1
/usr/share/man/man1/unmunge.1
/usr/share/man/man7/munge.7
/usr/share/man/man8/munged.8
/usr/share/man/man8/mungekey.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/munge.service
